# Generated by Django 3.1.5 on 2021-02-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stored_quantity',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
